version: 2.1
jobs:
  build:
    docker:
        - image: circleci/node:13.8.0
    steps:
        - checkout     
        - run:
            npm i
            npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          npm i
          npm run test
  analyze:
    docker:
        - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          npm i
          npm run audit
workflows:
  main_work:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
